### ISSUE TITLE
Moodboard

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#1]
Lets start collecting some links/screenshots to some personal websites the you like. It doesn't have to be the whole site. Maybe you like the colors someone used or you like how they structured their page. Will use this as inspiration for you website. Make sure to leave a comment outlining what you liked about the particular aspect of the website. e.g. The animations felt great, I really like how their page is structured, etc.

**Comment by emilywestenbroek** [comment]
I looked specifically for sites made using Jekyll, and here's what I've found:

**Animations**
I liked the menu animation  --  http://ivanhoinacki.com/
The animation for elements as the screen loaded was interesting. I wish it was a little smoother though --  https://mmistakes.github.io/so-simple-theme/

**Color Scheme & Overall Feel**
All of these sites have a very clean layout, which I like. I also like the off-white/gray + lighter color titling.
http://dlimiter.net/
http://martinisoftware.com/
https://www.aniketpant.com/

**Banner**
I'm not opposed to a banner image, but am not hitched to the idea. They often seem to not age well -- http://moss.io/
