### ISSUE TITLE
Build out your footer

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#10]
Based on your wireframes in #2 add your social media icons to your footer. It looks like you are looking to use icons for your social media links.

I would recommend having a look at these https://github.com/edent/SuperTinyIcons/tree/master/images/svg

You can grab the ones you need and include them within your footer.

**Comment by emilywestenbroek** [comment]
Added a footer section to my index.html and about pages. I am not sure how to use the svgs you linked to in my footer yet though. How do I pull a copy from this person's github? I uploaded my footer as just some anchor tags right now.

**Comment by alexcarpenter** [comment]
Not a problem, I can show you how to include the svgs.

When making use of Jekyll, you already have a default layout, which will include your header and footer on each page, so your index.html and about.html pages don't need to include them.

**Comment by alexcarpenter** [comment]
To grab the SVG code you can go to the file within the github repo and copy the code from there and include it within your anchor tags.

Here is a link to the Github icon -
 https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/github.svg

**Comment by emilywestenbroek** [comment]
I doubt I have the syntax correct in the footer, but I've added those svgs to the footer file.

**Comment by alexcarpenter** [comment]
You got it, nice work!
