### ISSUE TITLE
Move header and footer to includes

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#12]
Once #9 and #10 are completed more your header and footer into includes https://jekyllrb.com/docs/includes/

**Comment by emilywestenbroek** [comment]
I just created an _includes folder and moved the index.html and about.html files into that.

**Comment by emilywestenbroek** [comment]
I just realized that I did not do what you intended here. I'll give that one a closer read and give it another try.

**Comment by emilywestenbroek** [comment]
Not sure if I did this correctly, because Atom doesn't seem to recognize the link between the files in the _includes folder and my index and about.html. All changes have been pushed.

**Comment by alexcarpenter** [comment]
You will want to move the header and footer includes to the default.html file.

So your default layout should look like this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ site.title }}</title>
</head>
<body>
  {% include header.html %}
    {{ content }}
  {% include footer.html %}
</body>
</html>
```

**Comment by emilywestenbroek** [comment]
Ah, that makes a ton more sense :) I wasn't quite sure why that page on the Jekyll site was so excited about the front matter section. Totally get it now! I've updated the default.html and deleted the <head> section from the other html pages.

**Comment by alexcarpenter** [comment]
Yeah, it is nice so you only have one place to update if you ever need to add a link to your header or footer.
