### ISSUE TITLE
Setup CSS

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#15]
Setting up scss for your site https://jekyllrb.com/docs/assets/#sassscss

**Comment by emilywestenbroek** [comment]
If you could take a look at my current file setup I'd appreciate it. At first I just added a css folder with a scss file inside of that, but then I realized that I'll probably want a partials folder, and have my css minified and linked to my scss files. I know in the class that I took with Jeremy this fall we used instructions from https://github.com/necolas/normalize.css to accomplish this, but I didn't want to head too far out on my own and mess things up. I've only ever linked css and scss files once before and I don't clearly remember/understand the process myself.

**Comment by emilywestenbroek** [comment]
When I look in the example branch at the default.html link to the css, the link is entered as /css/main.css -- however, it looks to me like this should be /css/main.scss. Am I missing something there, or was that just a typo?

Also, when I build the site on chrome none of the styling from _general.scss or _skip-to.scss seems to be importing. I don't immediately see why that is though.

**Comment by alexcarpenter** [comment]
That is because it needs to be a css file to be read by the browser. If you look in the `_site` folder after the site is built you will see the css file is transpiled from scss -> css.

**Comment by alexcarpenter** [comment]
It looks like you are missing the second quotation mark that is need right after site.baseurl.

currently:
`<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}>`

update:
`<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">`

**Comment by emilywestenbroek** [comment]
Thanks for that! I'll get that fixed!
