### ISSUE TITLE
Make your title an h1

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#16]
https://github.com/emilywestenbroek/emilywestenbroek.github.io/blob/6961ae3d6258cb258a4cac9ad7a04c11fa9509c8/_includes/header.html#L2

Right now you have the title of your website as a paragraph tag, you will want this to be an `<h1>` tag.

**Comment by emilywestenbroek** [comment]
Good call. Just updated that!
