### ISSUE TITLE
Include Jekyll SEO plugin

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#18]
This plugin will help generate all of the Open Graph tag needs for your sites SEO.

https://github.com/jekyll/jekyll-seo-tag

**Comment by emilywestenbroek** [comment]
I just added those bits of code to my gemfile and _config.yml file, and pushed that change. It looks like that's all that's necessary for installation, but please correct me if I'm wrong.

**Comment by alexcarpenter** [comment]
Now you will want to place this within the `head` tag.

`{% seo %}`

So it should look like:

```
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% seo %}
  <link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">
</head>
```

**Comment by emilywestenbroek** [comment]
Okay, I made that change!

**Comment by alexcarpenter** [comment]
You can remove the `<title>` tag that is right below the `{% seo %}` tag now.

That will be generated from the seo plugin.
