### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#2]
Once we get a good idea of what you want to build from #1. Sketch out some _really_ rough wireframes similar to what you see at the top of this post https://m.signalvnoise.com/the-fidelity-curve-weighing-the-costs-and-benefits-of-interface-design-mockups-b259634807e2

These should be really simple, mainly outlining the different parts you are looking to include on your website, e.g. here is where the main content will live, this sidebar will have links to my social accounts, etc.

Once you have those done, take a photo with your phone and include them here.

**Comment by emilywestenbroek** [comment]
Here are my initial wireframes. I don't think I need to start with more than two or three pages, to begin with. At this point I am not very active on social media or Github, so I didn't emphasize those too much. However, I thought I could provide another direct link to Github, etc in the 'about me' section.

![img_2688](https://user-images.githubusercontent.com/31036559/34919510-58a5c490-f933-11e7-9876-8be8045e776b.JPG)
![img_2690](https://user-images.githubusercontent.com/31036559/34919553-d0c592d4-f933-11e7-941c-852993cea2d0.jpg)

**Comment by alexcarpenter** [comment]
Nice! I will close out this issue, we will use these wireframes as a reference when you start building out your pages.
