### ISSUE TITLE
Output posts on homepage

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#21]
https://github.com/emilywestenbroek/emilywestenbroek.github.io/blob/00b3d20188e3b65ffada9d4fa3da2c6070f4ba4f/index.html#L9

Here are the docs on displaying entries on your homepage https://jekyllrb.com/docs/posts/#displaying-an-index-of-posts

**Comment by emilywestenbroek** [comment]
I added a <ul> for the three posts I've got prepped. I did not see anything that would let me have an automatically generated list of most recent posts.
