### ISSUE TITLE
Create a skip to link

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#23]
Once you create your main element from #22 lets add a skip to link to your site for accessibility.

Here is a quick video showing how https://www.youtube.com/watch?v=sac2majyv1w

**Comment by emilywestenbroek** [comment]
I added the appropriate html and css for this, but because my css and html aren't properly linked yet it's not showing up correctly when I load the page.

**Comment by alexcarpenter** [comment]
You will want `tabindex="-1"` on the main element, it looks like you have it set as `tabindex:"1"` at the moment.
