### ISSUE TITLE
Fix tabindex

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#24]
https://github.com/emilywestenbroek/emilywestenbroek.github.io/blob/3e104b97feb1aca14ae0446093f87d17a7667558/_layouts/default.html#L13

Current: `tabindex:"-1"`

Updates: `tabindex="-1"`

**Comment by emilywestenbroek** [comment]
I just pushed a change for this. Thanks!
