### ISSUE TITLE
How to learn js post missing .md

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#28]
This file won't show up because it is missing the `.md` extension

https://github.com/emilywestenbroek/emilywestenbroek.github.io/blob/develop/_posts/2018-02-09-how-to-learn-js-chris-ferdinandi

**Comment by emilywestenbroek** [comment]
I've caught myself doing this on accident several times. I'll keep an eye on it!
