### ISSUE TITLE
Make use of classes

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#31]
https://github.com/emilywestenbroek/emilywestenbroek.github.io/blob/9a91831eff83523c781e1e335b6732de1421cf4a/_scss/_header.scss#L1-L6

This bit of code highlighted above means _all_ `<header>`s within your site will have the styles applied above. It is best to use a class to apply these styles.

**Comment by emilywestenbroek** [comment]
I've updated this so I'm no longer generically styling all headers. Thanks for the reminder!
