### ISSUE TITLE
Remove button around href

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#32]
https://github.com/emilywestenbroek/emilywestenbroek.github.io/blob/976396fe5799ba1669a43106ae1cc6b9f0f0c7a6/index.html#L30

You will want to remove the button tag that is wrapping the href and apply the `.button` class to the href.

**Comment by emilywestenbroek** [comment]
Finally got around to taking care of this! I'm curious about non-essential tags like this. Do you prefer to avoid putting anchor tags inside of buttons and just style the anchor itself? Is there any benefit to doing things this way?

**Comment by alexcarpenter** [comment]
hm, typically you are going to use one or another. I haven't seen a use case to use an href inside of a button.

Typically buttons are used to submit forms or interact with the page.

hrefs are used for moving between pages or external pages.

**Comment by emilywestenbroek** [comment]
Makes sense. I guess since <a> tags and <nav> tags often are styled to look like buttons I just assumed many of them were buttons. Never assume!
