### ISSUE TITLE
Create a development branch

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#4]
We will want to start the development work on a separate branch instead of `master`. Once work is completed we can release those features to the master branch.

Create a development branch called `develop`:
```bash
git checkout -b develop
```

push the newly created `develop` branch to github:
```bash
git push origin develop
```

**Comment by emilywestenbroek** [comment]
Just made the new branch. Heading to set up Jekyll now.
