### ISSUE TITLE
Add a gitignore file

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#6]
There are some files that we don't want included within the repo. To exclude you can create a file in the root of your website folder called `.gitignore`. These files are used for your local development and not needed within the repo.

Inside the file you will want to exclude:

```
_site/
.sass-cache/
.jekyll-cache/
.jekyll-metadata
.DS_Store
```

Once you have created this file, delete the `_site` folder and the `.DS_Store` file and commit those changes to the repo.

**Comment by emilywestenbroek** [comment]
I've created the `.gitignore` file, but I don't see the following files:
.sass-cache/
.jekyll-cache/
.jekyll-metadata
.DS_Store

**Comment by alexcarpenter** [comment]
That's ok, they will start poping up when we start getting into some CSS.
