### ISSUE TITLE
Add your header and footer markup to your default layout

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#7]
Now that we have the basic Jekyll structure setup, we can now start to build some of your site components.

Following the wireframes from #2 add your `header` and `footer` markup to the `_layouts/default.html` template.

These should surround the `{{ content }}` tag.

```html
<body>
  <header>...</header>
  {{ content }}
  <footer>...</footer>
</body>
```
Don't worry about any styling at the moment. It's best to start with a solid markup foundation before we start to get into the CSS.

**Comment by emilywestenbroek** [comment]
Okay, I added the header and footer.
